name: Balok CI/CD

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

 
  workflow_dispatch:


jobs:
 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

  deploy:
    needs: [ tests ]
    runs-on: ubuntu-latest

  # steps:
  #   - name: 'SSH to Balok deploy server'
  #     uses: appleboy/ssh-action@main
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       passowrd: ${{ secrets.PASSWORD }}
  #       port: ${{ secrets.PORT }}
  #       script: |
  #         cd /var/www/balok.id
  #         ls -lah
